### ISSUE TITLE
Running quickstart without existing .coafile fails

### ISSUE THREAD

**Issue by co-robo** [coala/coala-quickstart#143]
Opened by @satwikkansal at [gitter/coala/coala](https://gitter.im/coala/coala?at=59774be9714ea96f781ee9c1)

**Comment by satwikkansal** [comment]
Logs: https://gist.github.com/satwikkansal/861c38a5ab736604376ab1162b610909

**Comment by satwikkansal** [comment]
It probably seems like some error from `coalib` in the logs which specifically occurs only when the .coafile is missing. I tried a bit but was not able to find out which part of code makes the behavior of logging module different when `.coafile` is absent.

**Comment by satwikkansal** [comment]
Okay, so adding the following line to coala_quickstart.py stopped those errors for me

```py
logging.basicConfig(stream=sys.stdout)
```

But I'm not sure why this happened and if it's the right solution for this issue than where exactly to put it.

**Comment by satwikkansal** [comment]
The only portion from the stack trace that I could find where logic differs with presence of absence of `.coafile` is https://github.com/coala/coala/blob/master/coalib/settings/ConfigurationGathering.py#L82 

If the coafile is not found when running quickstart, the code inside the `except` block is run and `{'default': Section('default')}` is returned.

**Comment by jayvdb** [comment]
Was this caused by a change in coala? If so, the fix should be in coala.

**Comment by satwikkansal** [comment]
coala-quickstart didn't use the development version of coala earlier,  so this issue was hidden before 3f197eb148150a8eb5004eab6a7bb0c99d2d9a80.

**Comment by satwikkansal** [comment]
As the issue seems related to `LogPrinter` and `logging` module, we can implement the suggested fix (https://github.com/coala/coala-quickstart/issues/143#issuecomment-317811351) in either coala_quickstart or in the `LogPrinter` class itself.

**Comment by satwikkansal** [comment]
It's very hard to pin point which commit in coalib might have revealed/caused this issue. I manually checked all recent commits of `ConfigurationGathering.py` and `LogPrinter.py` modules in coalib but none of them were responsible for this specific issue with logging in coala-quickstart.
