### ISSUE TITLE
Flexible user Input

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-quickstart#152]
The users should have more freedom while entering the values for the settings. 

Example, making them case-insensitive, allowing common aliases and short-forms (see distutils [strtobool](https://docs.python.org/2/distutils/apiref.html?highlight=distutils.util#distutils.util.strtobool) function)

**Comment by adtac** [comment]
Alternative: https://github.com/coala/coala/blob/86f05440f6331de88bcc9dbc5b57391955a8e0a1/coalib/misc/Constants.py#L31
