### ISSUE TITLE
Ignore files field is not created in interactive mode

### ISSUE THREAD

**Issue by hemangsk** [coala/coala-quickstart#157]
Steps to reproduce
```
mkdir project
cd project
touch a.html b.html c.html main.css
coala-quickstart
```
At ```Which files to ignore ?``` Enter
```
main.css
```

In the final coafile generated file, 
```
[all]
bears = coalaBear, LineCountBear, InvalidLinkBear, FilenameBear
files = **.html
max_lines_per_file = 40
[all.html]
bears = TextLintBear, HTMLLintBear, BootLintBear
files = **.html
```

There should also be ```ignore = main.css``` field in [all] section if I understand correctly, which is missing.

Additionally, In https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Settings.py#L64

```
iif not all_files.isdisjoint(gitignore_files):
            ignores.append(os.path.relpath(glob, project_dir))
```
checks whether all_files are disjoint with gitignore_files, if True means that ```all_files``` do not include any of the files in ```gitignore_files```. So in that case we should append ```glob``` path to ```ignores```, right ?

If this is an issue, I'll fix it as a part of https://github.com/coala/coala-quickstart/pull/156 which is kind of stuck due to it.

**Comment by satwikkansal** [comment]
Yeah this is bad,
Even I tried running quickstart in interactive mode, and it's not adding the ignore field.

**Comment by satwikkansal** [comment]
> checks whether all_files are disjoint with gitignore_files, if True means that all_files do not include any of the files in gitignore_files. So in that case we should append glob path to ignores, right?

The logic in that piece of code is confusing for me too. Let's have a conclusion at https://github.com/coala/coala-quickstart/pull/156#discussion_r130213126 :P

**Comment by ishanSrt** [comment]
@satwikkansal @hemangsk when it asks` Which files to ignore ?`. How does one specify more than one files? Can we enter globs over there instead? Can we enter more than one globs? I don't think just calling `ignore_globs=ask_question(....)` solves this problem as the globs are not evaluated and if more than one files are mentioned, I don't think there is any condition present to tackle that either https://github.com/coala/coala-quickstart/blob/50b358a60454932c0c33fe9443f305abd1103b11/coala_quickstart/generation/FileGlobs.py#L44

**Comment by ishanSrt** [comment]
for e.g.. when `get_gitignore_glob` is called it actually evaluates the globs https://github.com/coala/coala-quickstart/blob/50b358a60454932c0c33fe9443f305abd1103b11/coala_quickstart/generation/FileGlobs.py#L37

**Comment by ishanSrt** [comment]
@hemangsk @satwikkansal put *.css instead of main.css in your steps to reproduce and you will see that it doesn't evaluate globs

**Comment by satwikkansal** [comment]
hmm, if you're saying that the data input by `ask_question` isn't evaluated actually to check if that is actually a glob or some invalid string, then IMO, it's a separate issue in itself.

Here, the concern is, the `ignore_globs` being returned by the `get_project_files` function aren't reflected in the final output `.coafile`. These globs can either be due to `.gitignore` files if that's present, or otherwise we ask the question.

Now, it's your turn to investigate where does this `ignore_globs` information gets lost from fetching globs to actually writing them in the final `.coafile`. If we'd have known the reason, we'd have fixed it right away. Hope that helps.

**Comment by ishanSrt** [comment]
@satwikkansal I opened a separate issue for that but can you help me with my PR https://github.com/coala/coala-quickstart/pull/209 ? If I run `pytest --cov --cov-report html` it shows that my code coverage is 95% but codecov fails it with 85% codecoverage

**Comment by satwikkansal** [comment]
@ishanSrt It seems to be passing after https://github.com/coala/coala-quickstart/pull/209/commits/2dddc631c600dcaeda0144e2bc85efec7ccc5f22 :)

**Comment by ishanSrt** [comment]
@Makman2 same for this issue. It's not closed.
