### ISSUE TITLE
Change usage of LogPrinter

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-quickstart#158]
According to https://github.com/coala/coala/blob/master/coalib/output/printers/LogPrinter.py#L96 

> This class is deprecated and will be soon removed. To get logger use logging.getLogger(__name__). 

So all the usages of  `LogPrinter` class should be changed accordingly.

**Comment by satwikkansal** [comment]
Following are the files where deprecated `LogPrinter` class has been initialized:

https://github.com/coala/coala-quickstart/blob/master/tests/generation/SettingsFillingTest.py
https://github.com/coala/coala-quickstart/blob/master/tests/generation/Bears.py
https://github.com/coala/coala-quickstart/blob/master/tests/generation/FileGlobs.py
https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Settings.py
https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/coala_quickstart.py
https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Bears.py
https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/FileGlobs.py

I've tested for https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/coala_quickstart.py that replacing the initialization of `log_printer` with the object returned by `logging.getLogger(__name__)` works without breaking anything.

Similar changes might be done in the other files as well.

Though replacing it won't have any immediate effects, but imo this is a preventive step in case of removal of the `LogPrinter` class in future. 

cc @seeeturtle

**Comment by seeeturtle** [comment]
thanks @satwikkansal :smile:
