### ISSUE TITLE
Appveyor fails ocassionaly on 64-bit architecture

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-quickstart#171]
Appveyor fails despite of all the tests being successful. One such example being https://ci.appveyor.com/project/coala/coala-quickstart/build/1.0.146/job/7e4i8gql8mdp2kd7

importance/ high
difficulty/low

**Comment by satwikkansal** [comment]
Seems like https://github.com/coala/coala-quickstart/blob/master/.ci/run_with_env.cmd#L42 is hiding some potential error.

**Comment by satwikkansal** [comment]
Another instance https://ci.appveyor.com/project/coala/coala-quickstart/build/1.0.198/job/3et896b2pdwoc2ko

**Comment by jayvdb** [comment]
> Seems like /.ci/run_with_env.cmd@master#L42 is hiding some potential error.

Well if you dont know the problem, we cant mentor it yet.

I was referring to the very basic problem ; I've created a new issue for it : https://github.com/coala/coala-quickstart/issues/201

**Comment by jayvdb** [comment]
Whatever the problem was, after https://github.com/coala/coala-quickstart/pull/334 it is a very different problem, and `run_with_env.cmd` is unused and should be deleted soon-ish
