### ISSUE TITLE
Ignore globs are not added to the output .coafile

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-quickstart#173]
The ignore globs provided by user of detected from `.gitignore` are not reflected in the final generated `.coafile`. Verified this by running quickstart inside coala-quickstart repository itself.

difficulty/low
importance/ high

**Comment by vaibhavsingh97** [comment]
Can i work on this issue?

**Comment by ishanSrt** [comment]
@satwikkansal can you provide us with a sample or an example to demonstrate or recreate this problem?

**Comment by satwikkansal** [comment]
We have methods to generate ignore fields (see https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Settings.py#L39), but for some unknown reason (which you'll have to figure out) these ignore fields are not added to the final output `.coafile`

**Comment by ishanSrt** [comment]
@satwikkansal can you give me a short example on this? for e.g.. when you run quickstart inside coala-quickstart itself, this is my .coafile.new generated:

```
# Generated by coala-quickstart on 08 Dec 2017.
[all]
bears = InvalidLinkBear, coalaBear, LineCountBear, FilenameBear
files = **.js, **.c, **.yml, **.rst, **.html, **.py
max_lines_per_file = 5000
[all.python]
bears = DocumentationStyleBear, PycodestyleBear
files = **.py
language = all.python
[all.yaml]
bears = YAMLLintBear, TravisLintBear
files = **.yml
[all.c]
bears = GNUIndentBear, ClangComplexityBear, CSecurityBear, DocumentationStyleBear
files = **.c
language = all.c
[all.html]
bears = HTMLHintBear, BootLintBear, TextLintBear, HTMLLintBear
files = **.html
[all.javascript]
bears = JSComplexityBear, JSHintBear, PHPCodeSnifferBear
files = **.js
[all.restructuredtext]
bears = RSTcheckBear, TextLintBear, reSTLintBear
files = **.rst

```

What is missing here?

**Comment by ishanSrt** [comment]
@satwikkansal can you please provide me with an example? I ran the coala-quickstart in the coala-quickstart directory itself and my `.coafile.new` is:

```
# Generated by coala-quickstart on 08 Dec 2017.
[all]
bears = InvalidLinkBear, coalaBear, LineCountBear, FilenameBear
files = **.js, **.c, **.yml, **.rst, **.html, **.py
max_lines_per_file = 5000
[all.python]
bears = DocumentationStyleBear, PycodestyleBear
files = **.py
language = all.python
[all.yaml]
bears = YAMLLintBear, TravisLintBear
files = **.yml
[all.c]
bears = GNUIndentBear, ClangComplexityBear, CSecurityBear, DocumentationStyleBear
files = **.c
language = all.c
[all.html]
bears = HTMLHintBear, BootLintBear, TextLintBear, HTMLLintBear
files = **.html
[all.javascript]
bears = JSComplexityBear, JSHintBear, PHPCodeSnifferBear
files = **.js
[all.restructuredtext]
bears = RSTcheckBear, TextLintBear, reSTLintBear
files = **.rst
```
What is missing over here? Should there be something like `ignore=` and all the files from .`gitignore`?

**Comment by ishanSrt** [comment]
@satwikkansal please bear with me as this is the first time I am actually trying to solve an issue that is not fixing a typo in the documentation. Please tell me what else is expected in the `.coafile` or `.coafile.new`

**Comment by satwikkansal** [comment]
Hey @ishanSrt 

Ideally there should be an `ignore` field in the generated `.coafile` like [this](https://github.com/coala/coala/blob/master/.coafile#L3) which contains ignore globs from `.gitignore` files.

**Comment by satwikkansal** [comment]
> Should there be something like ignore= and all the files from .gitignore

Exactly

**Comment by ishanSrt** [comment]
assign me this issue

**Comment by satwikkansal** [comment]
@ishanSrt Please have a look at the discussion at which might be helpful to you https://github.com/coala/coala-quickstart/issues/157

**Comment by ishanSrt** [comment]
@satwikkansal I did look at it. Can you tell me what is meant by this: https://github.com/coala/coala-quickstart/pull/156#issuecomment-318803685. Never heard of this before.

**Comment by satwikkansal** [comment]
If you were asking about `codecov` it's a tool to check coverage of our tests.

**Comment by ishanSrt** [comment]
Yes, what is meant by coverage?

**Comment by satwikkansal** [comment]
Well, I can't explain you better than Google, http://lmgtfy.com/?q=code+coverage

**Comment by ishanSrt** [comment]
@satwikkansal if I have made changes in my local repository, how do I test them out? how do I make coala-quickstart run the code from my local repository and see if my changes are correct. also how do I debug the code? can I put some extra print statements in between to check the state of variables at different stages? This is needed primarily because the function https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Settings.py#L39 in its docstring doesn't;t define one of the parameters and I don't know how is it called

**Comment by ishanSrt** [comment]
actually I know from where that particular function is being called, its just that a function defined in the same file for e.g.. https://github.com/coala/coala-quickstart/blob/50b358a60454932c0c33fe9443f305abd1103b11/coala_quickstart/generation/Settings.py#L70. From where is it getting called?

**Comment by ishanSrt** [comment]
@satwikkansal how do I test my changes locally after making changes to my local repository?

**Comment by ishanSrt** [comment]
I tried running `python3 coala-quickstart.py` but it can't find many of the packages.

**Comment by satwikkansal** [comment]
> how do I test my changes locally after making changes to my local repository?

If you have installed the quickstart package using `-e` flag, your changes would automatically reflect if you run `coala-quickstart` as you would normally.

**Comment by ishanSrt** [comment]
@satwikkansal I don't remember that but by making changes in the local repository I mean I made the changes where I cloned the coala-quickstart repository i.e. on my desktop

**Comment by ishanSrt** [comment]
I definitely didn't install it using the `-e` flag as there was nothing mentioned on the `README.rst` file

**Comment by ishanSrt** [comment]
I am trying to reinstall coala-quickstart but it says that `-e requires an argument`

**Comment by ishanSrt** [comment]
wait I figured it out, the argument must be the path to my local repository

**Comment by ishanSrt** [comment]
@satwikkansal I don't think that its working. If I comment out this line can you tell me how to output some things like if want to know the state of a variable at some point. The normal print statement doesn't work. Will I have to use some printer class to output to the console? it should not generate a new `.coafile`. But it is generating that

**Comment by satwikkansal** [comment]
@ishanSrt It's probably because you are still using the pypi release of quickstart instead of the local repository one. Try uninstalling quickstart first and the install again with `-e` flag. And make sure you've activated your virtual environment.

**Comment by ishanSrt** [comment]
@satwikkansal to the argument of `-e` I gave the url to my local repository i.e. `~/Desktop/coala-quickstart` whereas I should have given the url to my forked repository i.e. `https://github.com/ishanSrt/coala-quickstart`. I am trying to fix this.

**Comment by ishanSrt** [comment]
I am trying to follow this:

> Once you have forked the repository you would like to modify, you can install a repository-backed version of the repository using
> 
> (coala-venv)$ pip3 install -e <path/to/forked/repository>
> You will then be able to edit the repository and have the changes take effect in your virtualenv immediately. You will also be able to use pip3 to manage your installation of the package should you need to install from a different source in the future.

what does `<path/to/forked/repository>` mean over here? because running `pip3 install coala-quickstart --pre -e https://github.com/ishanSrt/coala-quickstart` gives me `https://github.com/ishanSrt/coala-quickstart should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+`

**Comment by satwikkansal** [comment]
It should be the local folder path

**Comment by ishanSrt** [comment]
@satwikkansal its not working. Do the changes have to be on the master branch? I had already made the changes before install coala-quickstart again and I am on a different branch. My virtual environment is activated.

**Comment by satwikkansal** [comment]
The branching and staging doesn't matter. If you're following exactly similar process as in https://api.coala.io/en/latest/Developers/Development_Setup.html and making changes it __should__ work.

**Comment by ishanSrt** [comment]
@Makman2 my PR was cherrypicked by you, but it seems the issues are not closed.
