### ISSUE TITLE
Remove all instances of (code analysis application) from the repo

### ISSUE THREAD

**Issue by adtac** [coala/coala-quickstart#178]

**Comment by Divya063** [comment]
@adtac Can I get more information on this?

**Comment by adtac** [comment]
https://github.com/coala/coala-quickstart/search?utf8=%E2%9C%93&q=code+analysis+application&type= - basically remove all occurrences of "code analysis application" from the repo. It's a retro acronym that we don't use anymore.

**Comment by yashkgp** [comment]
Can I work on this issue?

**Comment by Divya063** [comment]
@adtac Thanks for the information

**Comment by RaiVaibhav** [comment]
@yashkgp always read the new comer guide first,in that you will know how to assign yourself to any issue 
by using corobo bot

**Comment by Divya063** [comment]
@adtac please review
