### ISSUE TITLE
Add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by co-robo** [coala/coala-quickstart#187]
Add a file named `ISSUE_TEMPLATE.md` which includes general information and guidelines for issue reporter, you can see ISSUE_TEMPLATE.md of `coala` repository for reference.
label: initiatives/gci
Opened by @Monal5031 at [gitter//Monal5031](https://gitter.im//Monal5031?at=59f33a174ff065ac188263e8)

**Comment by utkarsh2102** [comment]
I'm willing to take up the task.
Please assign the same to me?
