### ISSUE TITLE
Dependeny not able to install properly

### ISSUE THREAD

**Issue by sourabhtk37** [coala/coala-quickstart#189]
- While installing dependencies from `requirements.txt`, the dependency `coala_bears~=0.12.0.dev20170722110839` is not able to find the file `ignore.txt` as specified in the logs below:

```Collecting coala_bears~=0.12.0.dev20170722110839 (from -r requirements.txt (line 3))
  Using cached coala-bears-0.12.0.dev20171102011141.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Module coalib is not found. Cannot do version checking.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jix_o_/coala-bears/setup.py", line 49, in <module>
        with open('ignore.txt') as ignore:
    IOError: [Errno 2] No such file or directory: 'ignore.txt'
```

- And `lxml` requires the following system dependencies `libxml2` and `libxslt`.

**Comment by sourabhtk37** [comment]
The above issues with `coala-bears` seems to be due to python2 and works on python3 virtual environment.

**Comment by Makman2** [comment]
Python 2 is not supported by coala.

> And lxml requires the following system dependencies libxml2 and libxslt

Those packages can only be installed outside of pip, so we can't do anything about it (for now). You have to install them manually.

**Comment by Makman2** [comment]
Closing the issue, if you still have something left unanswered in your install process, feel free to reopen :+1:

**Comment by sourabhtk37** [comment]
>so we can't do anything about it (for now

You can specify it in the list of dependencies to be installed before installing coala-quickstart in setup instruction. What do you think? @Makman2

**Comment by Makman2** [comment]
The dependency list `requirements.txt` is only for pip packages. For other packages, this is often system-dependent. For our bears, we try specify those requirements regardless of OS, however we don't have a functioning system yet that allows to install them in one go automatically^^

**Comment by sourabhtk37** [comment]
See what I'm proposing is a small change maybe three or four lines in the documentation specifying the dependencies. For example lxml python package requires libxml2 as a system dependency, now specify a line in  docs saying what all are the dependencies that needs to installed. 
Just look at the BigchainDB docs [here](https://docs.bigchaindb.com/projects/py-driver/en/latest/quickstart.html#how-to-install-the-dependencies) to understand what i'm trying to say. 

>however we don't have a functioning system yet that allows to install them in one go automatically^^

There is a solution for everything. Where should I discuss about this for implementation?

**Comment by Makman2** [comment]
> For example lxml python package requires libxml2 as a system dependency, now specify a line in docs saying what all are the dependencies that needs to installed.

Ah I've misunderstood you, I thought you mean to write into our install scripts to install them automatically once you do `pip install ...`. So yeah, we could surely write those requirements into the docs.

> There is a solution for everything. Where should I discuss about this for implementation?

Sure there is, we have ongoing issues for that already. The main development happens at https://gitlab.com/coala/package_manager for those features, but this is more bears related.

**Comment by Makman2** [comment]
Please open a new clean issue for adding the system package requirements into the docs, so we have a single issue for a single thing. We shouldn't reuse this issue for that any more :)
