### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by co-robo** [coala/coala-quickstart#190]
Our style follows the example given on http://editorconfig.org/ for Python and YAML
label: difficulty/low initiatives/gci
Opened by @mohitkyadav at [Gitter](https://gitter.im//mohitkyadav?at=5a07259c540c78242def89fe)

**Comment by Makman2** [comment]
See editorconfig file in https://github.com/coala/coala

**Comment by jackthepirate6** [comment]
I would like to take this up.
