### ISSUE TITLE
AppVeyor Build failing most of the times for the same code for which it had passed earlier

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala-quickstart#210]
error log doesn't show anything wrong or failing, shows 
```
======================== 56 passed in 60.93 seconds ==========================
Command exited with code 1
```
importance/high

link: https://ci.appveyor.com/project/coala/coala-quickstart/build/1.0.267

**Comment by Makman2** [comment]
Link to build?

**Comment by ishanSrt** [comment]
added the link

**Comment by ishanSrt** [comment]
Problem still occurring almost 50% of the times i push to my PR

**Comment by satwikkansal** [comment]
Related: https://github.com/coala/coala-quickstart/issues/171

**Comment by ishanSrt** [comment]
it is not related to #171
