### ISSUE TITLE
`packaging` version conflicts

### ISSUE THREAD

**Issue by virresh** [coala/coala-quickstart#229]
coala-bears in pre-release depend on safety module, which in turn dictates that latest packaging version be installed in it's [setup.py](https://github.com/pyupio/safety/blob/1380740696100a5724c4f33c735df9364de77ddf/setup.py#L15)
Whereas coala version in pre-release requires packaging version to be compatible with 16.8

Thus when pip would generate a dependency graph, the selection of packaging version would be arbitrary
Leading to random failures

safety module doesn't really need packaging's latest version, so we can safely pin it to 16.8 for current purposes

Although we need to change this with the next coala-bears pre-release.

**Comment by ishanSrt** [comment]
related https://github.com/coala/coala-quickstart/issues/210
