### ISSUE TITLE
Fix comment typo in coala_quickstart/generation/Bears.py

### ISSUE THREAD

**Issue by tallicamike** [coala/coala-quickstart#240]
`selectecd_bears` -> `selected_bears` in https://github.com/coala/coala-quickstart/blob/6fbaebd6c5dd7a5a3b961d85b9194cba3254d594/coala_quickstart/generation/Bears.py#L153

**Comment by ishanSrt** [comment]
yes @jsecrest a maintainer will fix that, the bot messes up sometimes 🙄

**Comment by utkarsh2102** [comment]
Can I take up this task?
