### ISSUE TITLE
Discrepancy in help message

### ISSUE THREAD

**Issue by djmgit** [coala/coala-quickstart#252]
When we run coala-quickstart, at first it asks for project directory and at that time it shows no hint or help message as what is project directory. After entering (or not entering) the project directory, there appears an help message telling what we should enter for the next question (files to ignore) and what we should enter for the first question which is quite odd as the user has already entered the answer to the first question!
![coala](https://user-images.githubusercontent.com/16368427/41114995-b466b280-6aa3-11e8-89d8-001e361dd45e.png)

The above mentioned behavior can be mentioned in the above screen shot. There should be a separate help message for the first question shown when the first question itself is asked.

**Comment by djmgit** [comment]
I would like to work on this.

**Comment by jayvdb** [comment]
@djmgit , I've invited you to the org. let me know when you've accepted it so I can assign you to issues.

**Comment by djmgit** [comment]
@jayvdb I have accepted your invitation.
