### ISSUE TITLE
Settings.py: Unused variables

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-quickstart#264]
Pyflakes error report =>
```
./generation/Settings.py:55: local variable 'all_files' is assigned to but never used
./generation/Settings.py:62: local variable 'gitignore_files' is assigned to but never used
```
Fix errors and run `pyflakes==2.0.0` to ensure all are resolved.
difficulty/newcomer

**Comment by sjha2000** [comment]
please assign me this issue

**Comment by ishanSrt** [comment]
ping @adtac 
maybe there were there to extend it in the future?

**Comment by jayvdb** [comment]
These variables were added in the first version 7c98e485 , and they were used within the logic.

6adab903 is the commit which made `all_files` and `gitignore_files` unused.

That is your puppy @ishanSrt ;-)

A quick squiz at the code changes you made and I think these are now useless and not likely to be ever helpful in this context.

I guess there must have been some reason why the logic was there, but it wasnt implemented correctly, and is not worth revisiting.

Just delete.

**Comment by sladyn98** [comment]
Assign me this one ill do it .
