### ISSUE TITLE
Zero questions mode

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-quickstart#39]
It should be possible to run this without any questions being asked.
It should make sensible decisions, and the user can edit the `.coafile` later when they better understand what the config options all mean.

This will allow https://github.com/coala/coala/wiki/Google-Code-In-Task-Use-coala to be an extremely easy task.

**Comment by sils** [comment]
uhm this is hard, @adtac is this doable within a week so it works? Doesn't have to be perfect.

**Comment by adtac** [comment]
Yeah, for the questions thing - the type is the only data we have about a particular setting. If we have a set of possible values (like aspects currently do) for each setting, it's pretty easy. So I'm wondering if we should put more resources into completing aspects or do this first.

**Comment by jayvdb** [comment]
In tbis mode, if a bear needs a user answer, dont enable that bear.

**Comment by jayvdb** [comment]
A little analysis shows this is easy, and is effectively:

```diff
     relevant_bears = filter_relevant_bears(used_languages)
+    if zeroconf_mode:
+         relevant_bears = [bear for bear in relevant_bears
+                          if not bear.get_non_optional_settings()]
     print_relevant_bears(printer, relevant_bears)
```

Some arg parsing is also needed.

**Comment by jayvdb** [comment]
I'm not 100% locked into `--ci ` CLI arg, and it is a bit cryptic.
`--non-interactive ` is descriptive and fairly commonly used.
It would be nice if this mode was also available for `coala`, which would be the same as "reject all questions and do the most logic thing."

It would be easier to use the `CI` envvar, which exposes tge functionality without needing for pick the CLI arg design.

**Comment by tulphoon** [comment]
@jayvdb While we have this mode already for `coala` and it's called `--ci`, for this one `--non-interactive` would have more sense in my opinion. You are going to generate a `.coafile` once, so it has nothing to do with continuous integration.
