### ISSUE TITLE
ci mode needs to bypass the "files to ignore" question

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-quickstart#49]
After the [CI mode](https://github.com/coala/coala-quickstart/issues/39) has been added, there is one remaining question by quickstart: which files to ignore.

This question only appears if there is not a `.gitignore`.  That is git specific, which should be fixed.  As a result, a workaround is to `touch .gitignore`, which will create this file if it exists, and the empty file is enough.  A better workaround is to use a tool to generate a better `.gitignore`.

Also, the generic coala parameter `--ignore` doesnt work, even if the default arg parser is used.  Fixing this is probably the best way to resolve this bug.

**Comment by sils** [comment]
CC @andreiraduta1101

**Comment by marian-ald** [comment]
I'll try to fix this

**Comment by adtac** [comment]
@marian-ald sure! I've assigned you this. If this is your first issue, take a look at coala.io/newcomer and if you get stuck anywhere, just ask on our Gitter channel :)

**Comment by marian-ald** [comment]
Thanks :+1:  :smile:

**Comment by marian-ald** [comment]
@jayvdb  Let's say I create a .gitignore file with 'touch'. What do you mean by "better .gitignore"?

**Comment by adtac** [comment]
maybe a project specific gitignore file? For example node projects usually have a `node_modules` directory that should be in gitignore. If we have a tool that can recognizeif a project is a node project, then it can generate a relevant gitignore automatically.

**Comment by jayvdb** [comment]
See https://github.com/github/gitignore

**Comment by marian-ald** [comment]
I'm a little bit confused... There are a lot of gitignore files types in this project(github/gitignore). Should I modify the existing .gitignore from coala-quickstart/  and add some other files, or to reorganize it?

**Comment by jayvdb** [comment]
This issue is not about the .gitignore in the coala-quickstart repo.
This issue is about bypassing the "files to ignore" question when coala-quickstart runs in CI mode.  In CI mode, there is no user to answer the question.  The process hangs indefinitely waiting for a user.

**Comment by marian-ald** [comment]
Aaa... so it's something in coala-quickstart.py I guess

**Comment by marian-ald** [comment]
Finally, I understood what  the problem is. I can bypass the question, no problem.
So when coala runs in in CI mode, if there is a .gitignore file, file globs expressions are loaded from .gitignore. But if there is not a .gitignore, I should generate one, it's ok this?  But I'm not sure how could I generate it...
@jayvdb You said it's enough to create  it, it's ok if I just bypass the question and create the empty .gitignore?
Also @adtac

**Comment by adtac** [comment]
@marian-ald creating an empty gitignore would automatically skip the question. What did you mean by

> it's ok if I just bypass the question and create the empty .gitignore?

**Comment by marian-ald** [comment]
You're right, it's the same thing :+1: 
So the question should be: It's ok if I just create the empty .gitignore?

**Comment by sils** [comment]
IMO it's not

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by adtac** [comment]
@marian-ald the tool is probably quite involved and surely beyond the scope of this issue. I just wanted to put the idea out there. (I'm thinking it could even be a GSoC project? CC @sils)

And indeed, they're not the same thing - creating an empty gitignore is probably just a workaround. Skipping the question without a gitignore is the better way (just do the "are we in CI mode" you'd do to create a gitignore at the place of the question).
