### ISSUE TITLE
Spelling mistake in README.rst

### ISSUE THREAD

**Issue by Flap-Py** [coala/coala-quickstart#81]
change 'do' -> 'to'

![image](https://cloud.githubusercontent.com/assets/11754275/24290687/dd4d17e6-10ab-11e7-82fd-de0b51786d11.png)

difficulty/newcomer

**Comment by RonnanSouza** [comment]
Please, assign me on this

**Comment by Flap-Py** [comment]
@RonnanSouza Hey for getting assigned, first you need to get invited to the organisation. Join [chat room](https://coala.io/chat)  to talk to the maintainers and one of them will invite you. In the meantime go through [newcomer guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html)

**Comment by fragm3** [comment]
Assign me on this!

**Comment by adtac** [comment]
Unassigning @RonnanSouza since he's closed his PR.
