### ISSUE TITLE
Validate user's input

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-quickstart#88]
Currently, the user inputs for the values of the settings are not validated and directly are directly written in the generated ".coafile". We need a way to validate those inputs first.

status/needs design

**Comment by meetmangukiya** [comment]
:+1: we can check the exit codes and only if it is successful it'll save ?

**Comment by satwikkansal** [comment]
But if it's not successful, how will the user know what went wrong? imo, we need a mechanism like
- user inputs value of a setting.
- The value is checked for the correct data-type.
- The value is also checked for functional correctness (not sure how to check this)
- If the value has any discrepancy, display an appropriate message and ask the user to enter it again.
- Finally, after all the values have been entered , check the exit code and save the .coafile if successful.
